version: "2"

services:

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
        - ./mysql:/var/lib/mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: javaee 
        MYSQL_USER: javaee 
        MYSQL_PASSWORD: eeavaj 

