

# This file was *autogenerated* from the file assignment_5.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_512 = Integer(512); _sage_const_511 = Integer(511); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_16 = Integer(16)
from sage.all import *

# Function to generate key pairs
def generate_keys():
    p = random_prime(_sage_const_2 **_sage_const_512 , False, _sage_const_2 **_sage_const_511 )
    q = random_prime(_sage_const_2 **_sage_const_512 , False, _sage_const_2 **_sage_const_511 )
    N = p * q
    phi = (p - _sage_const_1 ) * (q - _sage_const_1 )
    d = randint(_sage_const_2 , phi)
    while gcd(d, phi) != _sage_const_1 :
        d = randint(_sage_const_2 , phi)
    e = inverse_mod(d, phi)
    return N, e, d, p, q

# Function to sign a message using CRT
def sign_message(msg, N, d, p, q, error=_sage_const_0 ):
    m = Integer(msg.encode("utf-8").hex(), _sage_const_16 )
    sp = power_mod(m, d % (p - _sage_const_1 ), p) + error
    sq = power_mod(m, d % (q - _sage_const_1 ), q)
    s = crt([sp, sq], [p, q]) % N
    
    return (s, sp)

# Function to recover factorization from s and sp_error using Bellcore attack
def recover_factorization(N, sp_error, sq, p, q):
    # Compute u = (s % q) * (q^-1 % p) mod p
    u = (sq * inverse_mod(q, p)) % p

    # Compute v = (sp_error % p) * (p^-1 % q) mod q
    v = (sp_error * inverse_mod(p, q)) % q

    # Compute x = (u * q * p + v * p) mod N
    x = (u * q * p + v * p) % N

    # Compute y = (x % 2p) - p
    y = (x % (_sage_const_2  * p)) - p

    gcd_val = _sage_const_0 

    # Keep looping until gcd is not equal to 1 and not equal to N
    while gcd_val == _sage_const_0  or gcd_val == _sage_const_1  or gcd_val == N:
        y += _sage_const_2  * p
        gcd_val = gcd(x + y, N)

    factors = [gcd_val, N // gcd_val]
    return factors

# Function to detect error in sp
def detect_error(s, s_error):
    if s != s_error:
        return True
    else:
        return False


# Generate key pairs
N, e, d, p, q = generate_keys()

# Sign a message using CRT
msg = "Hello, world!"
s1, sp1 = sign_message(msg, N, d, p, q)
print("Signature:", s1)

# Simulate error in sp
print("Simulate error in sp")
error = randint(_sage_const_1 , p - _sage_const_1 )
s2, sp2 = sign_message(msg, N, d, p, q, error)
print("Signature:", s2)

# Recover factorization from s and sp using Bellcore attack
factorization = recover_factorization(N, sp2, s2, p, q)
print("Recovered Factorization:", factorization)

# Detect error in sp, by comparing the signtures s1 with s2
error_detected = detect_error(s1, s2)
print(error_detected)

