version: '3'

services:
    springboot:
        build: .
        depends_on:
            - db
        restart: always
        ports:
            - "8080:8080"
    db:
        image: mongo:5.0
        ports:
            - "27017:27017"
        restart: always
        container_name: mongo_db
