version: "3.2"

services:

  nodejs:
    build: ./node.js
    links:
         - redis
    ports:
         - 8080:8080
    volumes:
      - ./node.js:/src


  redis:
    image: "redis"
  nginx:
    build: ./nginx/
    ports:
       - 80:80
    depends_on:
       - nodejs 
    links:
       - nodejs
